stripe_config: 
  N_RUs: 20 #per stripe (20)
  N_stripes: 6 
  space_between_RUs: 1 #m
  space_between_stripes: 1 #m
  stripe_start_pos: [2, 2.5, 3.5] #x,y,z
  array_direction: 'x' # direction along which the antennas of the array are placed 'x' => perpendicular to stripe direction (y) note this argument is fixed! only 'x' is supported for now

antenna_config: 
  N_antennas: 4
  pattern: 'measured'
  polarization: 'V'

subTHz_config:
  fc:  157.75e+9 
  bw:  3.0e+9 #6.0e+9 
  num_subcarriers: 4096 #1024
  doppler: False # todo add

sub10GHz_config:
  fc:  3.5e+9 
  bw:  20.0e+6 
  num_subcarriers: 1024 
  num_APs : 4 # number of APs in the scene
  ap_pos_ceil_1: [5.25, 7.25, 3.5] # xyz
  ap_pos_ceil_2: [5.25, 18.25, 3.5] # xyz
  ap_pos_wall_1: [2, 13, 2.5] # xyz
  ap_pos_wall_2: [5.25, 23.5, 2.5] # xyz


ue_locations_config:
  num_locations_zone1: 2000 #3000 #other locations are computed based on area
 # total number will be ~ num_locations_zone1 * 1.712 + N_RUs*N_stripes
paths:
  basepath: "/home/user/6GTandem_RT_server/datasets_mobility_rad_pat"
  scenepath: "/home/user/6GTandem_RT_server/6G_Tandem_kantoorruimte_v10/office_space.xml"
  antenna_rad_path: "/home/user/6GTandem_RT_server/antenna_patterns"


random_configs:
  intermediate_renders: False # intermediatelly render the scene
  ue_orientation: 'up' #ue array is pointed upward (not used just as FYI)
  RU_orientation: 'down' #ru array is pointed downward (not used just as FYI)
  batch_size: 5 #number of RUs to process in parallel (depends on RAM/GPU memory)